language: python

python:
  - "2.7"

cache: pip

sudo: false

matrix:
  include:
    - env: TOX_ENV=py27-dj18-sqlite
    - env: TOX_ENV=py27-dj18-mysql
    - env: TOX_ENV=py27-dj18-postgres
    - env: TOX_ENV=py27-dj110-sqlite
    - env: TOX_ENV=py27-dj110-mysql
    - env: TOX_ENV=py27-dj110-postgres
    - env: TOX_ENV=py34-dj18-sqlite
    - env: TOX_ENV=py34-dj18-mysql
    - env: TOX_ENV=py34-dj18-postgres
    - env: TOX_ENV=py34-dj110-sqlite
    - env: TOX_ENV=py34-dj110-mysql
    - env: TOX_ENV=py34-dj110-postgres
    - env: TOX_ENV=py27-dj18-contrib-sqlite
    - env: TOX_ENV=py27-dj18-contrib-mysql
    - env: TOX_ENV=py27-dj18-contrib-postgres
    - env: TOX_ENV=py27-dj110-contrib-sqlite
    - env: TOX_ENV=py27-dj110-contrib-mysql
    - env: TOX_ENV=py27-dj110-contrib-postgres
    - env: TOX_ENV=py34-dj18-contrib-sqlite
    - env: TOX_ENV=py34-dj18-contrib-mysql
    - env: TOX_ENV=py34-dj18-contrib-postgres
    - env: TOX_ENV=py34-dj110-contrib-sqlite
    - env: TOX_ENV=py34-dj110-contrib-mysql
    - env: TOX_ENV=py34-dj110-contrib-postgres
    - language: node_js
      node_js: "0.10.40"
      script: make test-js
      install: echo "nothing to install"

before_install:
  - cat "$TRAVIS_BUILD_DIR/travis/my.cnf" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart

install:
  - pip install --upgrade pip
  - pip install tox

before_script:
  - psql -c 'create database widgy;' -U postgres
  - mysql -e 'create database widgy;'

script:
  - tox -e $TOX_ENV

after_script:
  - cat .tox/$TOX_ENV/log/*.log
